### ISSUE TITLE
The layout is broken in Yahoo! JAPAN

### ISSUE THREAD

**Issue by munierujp** [wong2/chatgpt-google-extension#332]
**Describe the bug**
The layout is broken in Yahoo! JAPAN.
To fix it, apply these styles:

```css
#chat-gpt-for-google-search-enhance {
}

.search-enhance-WDIEk {
  width: 450px;
}
```

|before|after|
|---|---|
|![chatgpt_yahoo_2](https://user-images.githubusercontent.com/20086673/224988320-80bae915-c9e1-41e8-853a-18fa706a9363.png)|![chatgpt_yahoo_1](https://user-images.githubusercontent.com/20086673/224988287-fc4189d8-deb4-45b7-9c48-d09c89478d58.png)|

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1（22D68）
 - Browser Chrome 110.0.5481.177
