### ISSUE TITLE
The layout is broken in Yahoo! JAPAN

### ISSUE THREAD

**Issue by munierujp** [wong2/chatgpt-google-extension#333]
**Describe the bug**
The layout is broken in Yahoo! JAPAN.
To fix it, apply these styles:

```css
#chat-gpt-for-google-search-enhance {
  margin-left: 20px;
}

.search-enhance-WDIEk {
  width: 450px;
}
```

|before|after|
|---|---|
|![chatgpt_yahoo_1](https://user-images.githubusercontent.com/20086673/224989627-e19f5ad9-2d72-4062-a4a1-f82db0c06209.png)|![chatgpt_yahoo_2](https://user-images.githubusercontent.com/20086673/224989636-73ae714e-1a3d-4613-a347-9706a1ff7a28.png)|

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1（22D68）
 - Browser Chrome 110.0.5481.177
